services:
  web:
    platform: linux/arm64
    hostname: web
    container_name: web
    build:
      context: .
      dockerfile: dockerfile
      target: local
      args:
        ENV: local
        WORK_DIR: /workdir
        PYTHON_VERSION: 3.9.16
    ports:
      - 8000:8000
    volumes:
      - .:/workdir
    restart: unless-stopped